replicaCount: 1

image:
  repository: venkatesh1409/threadedtreasures
  tag: "0.0.1"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30007

ingress:
  enabled: true
  hostname: myapp.local # Change this to your desired hostname

resources: {}